export const refineResources = [
  {
    name: "customer",
    list: "/customer",
    create: "/customer/create",
    edit: "/customer/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "user",
    list: "/user",
    create: "/user/create",
    edit: "/user/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "product",
    list: "/product",
    create: "/product/create",
    edit: "/product/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "banner-type",
    list: "/banner-type",
    create: "/banner-type/create",
    edit: "/banner-type/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "business",
    list: "/business",
    create: "/business/create",
    edit: "/business/edit/:id",
  },
  {
    name: "category",
    list: "/category",
    create: "/category/create",
    edit: "/category/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "coupon-codes",
    list: "/coupon-codes",
    create: "/coupon-codes/create",
    edit: "/coupon-codes/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "currency",
    list: "/currency",
    create: "/currency/create",
    edit: "/currency/edit/:id",
  },
  {
    name: "banner",
    list: "/banner",
    create: "/banner/create",
    edit: "/banner/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "locale",
    list: "/locale",
    create: "/locale/create",
    edit: "/locale/edit/:id",
  },
  {
    name: "store-feature",
    list: "/store-feature",
    create: "/store-feature/create",
    edit: "/store-feature/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "store",
    list: "/store",
    create: "/store/create",
    edit: "/store/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "store-banner",
    list: "/store-banner",
    create: "/store-banner/create",
    edit: "/store-banner/edit/:id",
    meta: { canDelete: true },
  },
];
