export const refineResources = [
  {
    name: "customers",
    list: "/customers",
    create: "/customers/create",
    edit: "/customers/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "users",
    list: "/users",
    create: "/users/create",
    edit: "/users/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "products",
    list: "/products",
    create: "/products/create",
    edit: "/products/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "banner_types",
    list: "/banner-types",
    create: "/banner-types/create",
    edit: "/banner-types/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "businesses",
    list: "/businesses",
    create: "/businesses/create",
    edit: "/businesses/edit/:id",
  },
  {
    name: "categories",
    list: "/categories",
    create: "/categories/create",
    edit: "/categories/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "coupon_codes",
    list: "/coupon-codes",
    create: "/coupon-codes/create",
    edit: "/coupon-codes/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "currencies",
    list: "/currencies",
    create: "/currencies/create",
    edit: "/currencies/edit/:id",
  },
  {
    name: "locales",
    list: "/locales",
    create: "/locales/create",
    edit: "/locales/edit/:id",
  },
  {
    name: "store_features",
    list: "/store-features",
    create: "/store-features/create",
    edit: "/store-features/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "stores",
    list: "/stores",
    create: "/stores/create",
    edit: "/stores/edit/:id",
    meta: { canDelete: true },
  },
  {
    name: "store_banners",
    list: "/store-banners",
    create: "/store-banners/create",
    edit: "/store-banners/edit/:id",
    meta: { canDelete: true },
  },
];
